apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyobs-frontend-deployment
  labels:
    app: easyobs-frontend
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easyobs-frontend
  template:
    metadata:
      labels:
        app: easyobs-frontend
    spec:
      volumes:
      - name: config-vol
        configMap:
          name: easyobs-fronend-config
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-vol
          mountPath: /app/.env
          subPath: .env
---
apiVersion: v1
kind: Service
metadata:
  name: easyobs-frontend-svc
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: easyobs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: easyobs-fronend-config
  namespace: "{{ .Release.Namespace }}"
data:
  .env: |
    VITA_CONTROLLER_API_HOST=easyobs-controller-svc.local
    VITA_CONTROLLER_API_PORT=30973