apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easyobs-controller-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: "{{ .Release.Namespace }}"
spec:
  rules:
    - host: easyobs-controller-svc.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: easyobs-controller-svc
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easyobs-controller-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: "{{ .Release.Namespace }}"
spec:
  rules:
    - host: easyobs-frontend-svc.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: easyobs-frontend-svc
                port:
                  number: 80