# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/data.proto\x12\x04\x64\x61ta\x1a\x1cgoogle/protobuf/struct.proto\"1\n\x04\x44\x61ta\x12)\n\x08Metadata\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x18\n\x06Status\x12\x0e\n\x06Status\x18\x01 \x01(\x05\x32\x31\n\x0b\x44\x61taService\x12\"\n\x04Send\x12\n.data.Data\x1a\x0c.data.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATA']._serialized_start=56
  _globals['_DATA']._serialized_end=105
  _globals['_STATUS']._serialized_start=107
  _globals['_STATUS']._serialized_end=131
  _globals['_DATASERVICE']._serialized_start=133
  _globals['_DATASERVICE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
