apiVersion: v2
name: easyobs
description: Observability on K8s using eBPF
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: redis-ha
    version: 4.23.0
    repository: https://dandydeveloper.github.io/charts/
    condition: redis-ha.enabled
